theme: jekyll-theme-minimal
title: Witajcie na stronie Artura Rutkowskiego, który bardzo kocha swoją wspaniałą dziewczynę Marię, nie Marysię.
description: Strona w budowie (gdybym umiał wstawić, to tutaj wstawiłbym obrazek z Bobem Budowniczym.)
